# Medical Fraud Detection
## 13038 instances

In [1]:
import warnings
warnings.filterwarnings('ignore')

## Data Loading and Cleaning

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import MinMaxScaler

In [3]:
df=pd.read_csv("C://Users//250228//Desktop//Codes//Python//Medical Fraud Detection//MedicalFraud1.csv")
df.head()

creditLimit  availableMoney transactionDateTime  transactionAmount  \
0         5000          5000.0    13-08-2016 14:27              98.55   
1         5000          5000.0    11-10-2016 05:05              74.51   
2         5000          5000.0    08-11-2016 09:18               7.47   
3         5000          5000.0    10-12-2016 02:14               7.47   
4         5000          5000.0    24-03-2016 21:04              71.18   

          merchantName acqCountry merchantCountryCode  posEntryMode  \
0                 Uber         US                  US           2.0   
1          AMC #191138         US                  US           9.0   
2           Play Store         US                  US           9.0   
3           Play Store         US                  US           9.0   
4  Tim Hortons #947751         US                  US           2.0   

   posConditionCode merchantCategoryCode  ... accountOpenDate  \
0               1.0            rideshare  ...      14-03-2015   
1               1.0        entertainment  ...      14-03-2015   
2               1.0           mobileapps  ...      14-03-2015   
3               1.0           mobileapps  ...      14-03-2015   
4               1.0             fastfood  ...      06-08-2015   

  dateOfLastAddressChange cardCVV  enteredCVV  cardLast4Digits  \
0              14-03-2015     414         414             1803   
1              14-03-2015     486         486              767   
2              14-03-2015     486         486              767   
3              14-03-2015     486         486              767   
4              06-08-2015     885         885             3143   

   transactionType currentBalance  cardPresent  expirationDateKeyInMatch  \
0         PURCHASE            0.0            0                         0   
1         PURCHASE            0.0            1                         0   
2         PURCHASE            0.0            0                         0   
3         PURCHASE            0.0            0                         0   
4         PURCHASE            0.0            1                         0   

   Fraud  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 21 columns]

In [4]:
df['transactionDateTime'] = df['transactionDateTime'].str.replace('-', '').str.replace(':', '').str.replace(' ', '')
df['currentExpDate'] = df['currentExpDate'].str.replace('-', '')
df['accountOpenDate'] = df['accountOpenDate'].str.replace('-', '')
df['dateOfLastAddressChange'] = df['dateOfLastAddressChange'].str.replace('-', '')
df.head()

creditLimit  availableMoney transactionDateTime  transactionAmount  \
0         5000          5000.0        130820161427              98.55   
1         5000          5000.0        111020160505              74.51   
2         5000          5000.0        081120160918               7.47   
3         5000          5000.0        101220160214               7.47   
4         5000          5000.0        240320162104              71.18   

          merchantName acqCountry merchantCountryCode  posEntryMode  \
0                 Uber         US                  US           2.0   
1          AMC #191138         US                  US           9.0   
2           Play Store         US                  US           9.0   
3           Play Store         US                  US           9.0   
4  Tim Hortons #947751         US                  US           2.0   

   posConditionCode merchantCategoryCode  ... accountOpenDate  \
0               1.0            rideshare  ...        14032015   
1               1.0        entertainment  ...        14032015   
2               1.0           mobileapps  ...        14032015   
3               1.0           mobileapps  ...        14032015   
4               1.0             fastfood  ...        06082015   

  dateOfLastAddressChange cardCVV  enteredCVV  cardLast4Digits  \
0                14032015     414         414             1803   
1                14032015     486         486              767   
2                14032015     486         486              767   
3                14032015     486         486              767   
4                06082015     885         885             3143   

   transactionType currentBalance  cardPresent  expirationDateKeyInMatch  \
0         PURCHASE            0.0            0                         0   
1         PURCHASE            0.0            1                         0   
2         PURCHASE            0.0            0                         0   
3         PURCHASE            0.0            0                         0   
4         PURCHASE            0.0            1                         0   

   Fraud  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 21 columns]

In [5]:
scaler = MinMaxScaler()
columns_to_scale = ["creditLimit", "availableMoney", "transactionAmount", "cardCVV", "enteredCVV", "cardLast4Digits", "currentBalance"]
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])
df = df.dropna()
df.head()

creditLimit  availableMoney transactionDateTime  transactionAmount  \
0     0.095477        0.117744        130820161427           0.048992   
1     0.095477        0.117744        111020160505           0.037041   
2     0.095477        0.117744        081120160918           0.003714   
3     0.095477        0.117744        101220160214           0.003714   
4     0.095477        0.117744        240320162104           0.035386   

          merchantName acqCountry merchantCountryCode  posEntryMode  \
0                 Uber         US                  US           2.0   
1          AMC #191138         US                  US           9.0   
2           Play Store         US                  US           9.0   
3           Play Store         US                  US           9.0   
4  Tim Hortons #947751         US                  US           2.0   

   posConditionCode merchantCategoryCode  ... accountOpenDate  \
0               1.0            rideshare  ...        14032015   
1               1.0        entertainment  ...        14032015   
2               1.0           mobileapps  ...        14032015   
3               1.0           mobileapps  ...        14032015   
4               1.0             fastfood  ...        06082015   

  dateOfLastAddressChange   cardCVV  enteredCVV  cardLast4Digits  \
0                14032015  0.349666    0.414830         0.180336   
1                14032015  0.429844    0.486974         0.076715   
2                14032015  0.429844    0.486974         0.076715   
3                14032015  0.429844    0.486974         0.076715   
4                06082015  0.874165    0.886774         0.314363   

   transactionType currentBalance  cardPresent  expirationDateKeyInMatch  \
0         PURCHASE            0.0            0                         0   
1         PURCHASE            0.0            1                         0   
2         PURCHASE            0.0            0                         0   
3         PURCHASE            0.0            0                         0   
4         PURCHASE            0.0            1                         0   

   Fraud  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 21 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df['merchantName']=le.fit_transform(df['merchantName'])
df['transactionType']=le.fit_transform(df['transactionType'])
df['merchantCategoryCode']=le.fit_transform(df['merchantCategoryCode'])
df['acqCountry']=le.fit_transform(df['acqCountry'])

df.head()

creditLimit  availableMoney transactionDateTime  transactionAmount  \
0     0.095477        0.117744        130820161427           0.048992   
1     0.095477        0.117744        111020160505           0.037041   
2     0.095477        0.117744        081120160918           0.003714   
3     0.095477        0.117744        101220160214           0.003714   
4     0.095477        0.117744        240320162104           0.035386   

   merchantName  acqCountry merchantCountryCode  posEntryMode  \
0          2085           3                  US           2.0   
1            27           3                  US           9.0   
2          1304           3                  US           9.0   
3          1304           3                  US           9.0   
4          2083           3                  US           2.0   

   posConditionCode  merchantCategoryCode  ... accountOpenDate  \
0               1.0                    17  ...        14032015   
1               1.0                     3  ...        14032015   
2               1.0                    12  ...        14032015   
3               1.0                    12  ...        14032015   
4               1.0                     4  ...        06082015   

  dateOfLastAddressChange   cardCVV  enteredCVV  cardLast4Digits  \
0                14032015  0.349666    0.414830         0.180336   
1                14032015  0.429844    0.486974         0.076715   
2                14032015  0.429844    0.486974         0.076715   
3                14032015  0.429844    0.486974         0.076715   
4                06082015  0.874165    0.886774         0.314363   

   transactionType  currentBalance  cardPresent  expirationDateKeyInMatch  \
0                1             0.0            0                         0   
1                1             0.0            1                         0   
2                1             0.0            0                         0   
3                1             0.0            0                         0   
4                1             0.0            1                         0   

   Fraud  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 21 columns]

In [7]:
X = df.drop(["Fraud","merchantCountryCode"], axis=1)
y = df["Fraud"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [11]:
y_pred = lr.predict(X_test)

In [12]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_report_str = classification_report(y_test, y_pred)

In [13]:
accuracy

0.9843992085870876

In [14]:
confusion

array([[229366,      0],
       [  3635,      0]], dtype=int64)

## Decision Tree

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [17]:
y_pred_tree = decision_tree_model.predict(X_test)

In [18]:
accuracy_tree = accuracy_score(y_test, y_pred_tree)
confusion_tree = confusion_matrix(y_test, y_pred_tree)

In [19]:
accuracy_tree

0.9701889691460551

In [20]:
confusion_tree

array([[225436,   3930],
       [  3016,    619]], dtype=int64)

## Random Forest Classification

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
random_forest_model = RandomForestClassifier(n_estimators=20)
random_forest_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [23]:
y_pred_forest = random_forest_model.predict(X_test)

In [24]:
accuracy_forest = accuracy_score(y_test, y_pred_forest)
confusion_forest = confusion_matrix(y_test, y_pred_forest)

In [25]:
accuracy_forest

0.9857039240174935

In [26]:
confusion_forest

array([[229357,      9],
       [  3322,    313]], dtype=int64)

## Gradient Boosting

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

In [28]:
gradient_boosting_model = GradientBoostingClassifier(n_estimators=20, learning_rate=0.1)
gradient_boosting_model.fit(X_train, y_train)

GradientBoostingClassifier(n_estimators=20)

In [29]:
y_pred_gradient = gradient_boosting_model.predict(X_test)

In [30]:
accuracy_gradient = accuracy_score(y_test, y_pred_gradient)
confusion_gradient = confusion_matrix(y_test, y_pred_gradient)

In [31]:
accuracy_gradient

0.9843992085870876

In [32]:
confusion_gradient

array([[229366,      0],
       [  3635,      0]], dtype=int64)

## Naive Bayes

In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train, y_train)

GaussianNB()

In [35]:
y_pred_naive_bayes = naive_bayes_model.predict(X_test)

In [36]:
accuracy_naive_bayes = accuracy_score(y_test, y_pred_naive_bayes)
confusion_naive_bayes = confusion_matrix(y_test, y_pred_naive_bayes)

In [37]:
accuracy_naive_bayes

0.9843992085870876

In [38]:
confusion_naive_bayes

array([[229366,      0],
       [  3635,      0]], dtype=int64)